default:
  tags:
    - $BUILD_TAGS

stages:
  - release

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event"
      when: never
    - when: always

release-chart:
  stage: release
  image: alpine/helm:3.15.2
  only:
    refs:
    - main
    changes:
    - dist/charts/ping-exporter/**/*
  script:
    - export RELEASE_VERSION=`grep version helm/Chart.yaml | cut -d ":" -f 2 | head -n1 | xargs`
    - apk add git
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add chart_repo $CHART_REPO_URL --username $CHART_REPO_USER --password $CHART_REPO_PASS
    - helm dependency build ./helm
    - helm package ./helm --version "$RELEASE_VERSION"
    - helm cm-push ./helm chart_repo --version "$RELEASE_VERSION" -f
